### ISSUE TITLE
Monitor temperature (nacelle + resistor cabinet) and rotor position

### ISSUE THREAD

**Issue by petebachant** [petebachant/TurbineDAQ#69]

**Comment by petebachant** [comment]
From @meganandd 

Possible duplicate of #66

**Comment by Pamboukes** [comment]
"load cell data" is captured in Issue #66.

In addition to load cell data, we would also like the ability to monitor (and record):

Temperature 4x:  T forward hull, T aft hull, T Resistor Cabinet, T Yaskawa Control Cabinet

Carriage speed (tow speed)

Rotor position

Rotor speed

monitoring includes numeric readout and Y vs X chart (Y is parameter of interest, X is time).  Generally, anything that is monitored should also be recorded.
