### ISSUE TITLE
TareDrag and TareTorque NI plots

### ISSUE THREAD

**Issue by meganandd** [petebachant/TurbineDAQ#90]
Katie's plan this AM was to run TareDrag and TareTorque tests, but noticed that the NI-DAQ (CFT) plots weren't updating during the actual tare drag tow. We did one run to completion, and the plots updated with data from the run once the carriage returned to the right limit. Data was also still being written to file. To keep her moving, I changed usetrigger from True to False for both tare run types so data collection would start on 'play' and that seemed to fix it for now. I think it might have to do with the AFT vs. CFT mode and how that affects NI sampling or it needs to sleep for longer? I also changed FVEL(5) to RVEL(5) in the tare_drag.prg and tare_torque.prg buffers so that would start updating as well.

**Comment by meganandd** [comment]
Steve and I tested tare drag and torque runs last week and noticed that the plots still weren't automatically updating when the run would start--just wanted to give you an update.

**Comment by petebachant** [comment]
It's seems that somewhere along the way the edge for the trigger pulse became different between the normal turbine tows and the tare runs. If the turbine tows are triggering properly, I will set the tare programs to match that logic.
