### ISSUE TITLE
ACS DC time dataset 

### ISSUE THREAD

**Issue by meganandd** [petebachant/TurbineDAQ#93]
As I was processing data from some runs, I looked closer at the time data points from ACS and noticed that they are all not unique. With some periodicity, the time array will be counting up in 0.001s increments (normal), before jumping ahead a tenth of a second or so, continuing to count in 0.001 s increments, and then falling back to the 'proper' time. I think this might be contributing to the weirdness with the turbine RPM/position data and how they tend to be spikey. The raw time array from ACS DC is also considerably shorter than it should be. For example, one run I looked at starts at 0 s and ends at 88.6780 s, but only contains 77700 points when it should be 88679 points long given the sampling rate and start/stop times. I've attached some screenshots to help explain what I'm seeing. Is this because of the 'sleep' commands that happen in daqtasks.py or how data is rewritten in the buffer once it's full? Let me know what you think and thank you so much!

This plot shows time vs. time array indices: 
<img width="422" alt="acs_time_vs_time_indices" src="https://github.com/petebachant/TurbineDAQ/assets/30161853/c8a3c0ab-322f-467c-beaf-3ab0c2d91fca">

This screenshot is from looking at a section of the time array in a table: 
<img width="354" alt="acs_time_weirdness" src="https://github.com/petebachant/TurbineDAQ/assets/30161853/2b31b7e8-2039-4d80-a4f4-11612778c2cd">

This plot is turbine position (1 unit = 6 degrees) vs. time:
<img width="443" alt="turbine_pos_weirdness" src="https://github.com/petebachant/TurbineDAQ/assets/30161853/344fba21-29b0-42fa-8d4c-88c76bc2b5a8">

**Comment by petebachant** [comment]
> Is this because of the 'sleep' commands that happen in daqtasks.py or how data is rewritten in the buffer once it's full?

This sounds like the most likely culprit. We are probably sleeping too long each iteration, so some samples in the buffer are overwritten before we get a chance to read them out. The difference in time taken could be due to the new firmware, so some trial and error may be in order to optimize the sleep time.

**Comment by meganandd** [comment]
Do you have any recommendations on what to change the sleep time to? I was going to play around with it today. Would another solution also be to increase the size of the data collection array in ACS from 100 to something larger?

**Comment by petebachant** [comment]
I would first try to get setup to where you can reproduce and detect the problem quickly and reliably. Can you instantiate one of these threads and detect if the time array is discontinuous using the `dev.ipynb` notebook? You could check something like `pd.DataFrame(thread.data).time.diff().unique()` to check that the unique values of the difference in time between samples is the same. 

Once you have a fixture that can reliably reproduce and detect the issue, ramp down the `1.05` factor used to compute the sleep time in the thread, maybe by 0.01 each try, until it's reliable. That's the naive approach that I most likely used to tune it originally. There may be a more direct "closed-loop" approach where you somehow detect if you're falling behind reading the buffer, and compute the sleep time each iteration, but I'm not sure if that would add too much overhead.

**Comment by meganandd** [comment]
I've been trying out some stuff and haven't had a ton of success. I'll attach some results with the conditions I used. 

Here is with bufflen = 100 and sleeptime = bufflen / sr / 2:
![bufflen_100](https://github.com/petebachant/TurbineDAQ/assets/30161853/33503c82-d183-4423-93c9-2ac0c357f34a)

Here is with bufflen = 100 and sleeptime = bufflen / sr / 2 * 0.95:
![bufflen_100_0 95](https://github.com/petebachant/TurbineDAQ/assets/30161853/b296d9dd-ade6-4815-a1e2-1705b3120eec)

Here is with bufflen = 500 and sleeptime = bufflen / sr / 2:
![bufflen_500](https://github.com/petebachant/TurbineDAQ/assets/30161853/cf81d14b-0ad1-4797-9a11-14e9e231b4f8)

The time scales aren't exactly the same, but what I've noticed is that with the smaller buffer length, the time jumping is more frequent despite how much I change that multiplier. As for the longer buffer length, there is a larger amount of time with no weirdness, but then it experiences a longer duration of time jumping.

**Comment by petebachant** [comment]
Very strange. Ultimately it seems like we aren't reading the buffer fast enough and a few samples are being overwritten by the next iteration. It might have something to do with the lines where we wait for data collection to start before trying to read anything:

```python
while not collecting_data():
    time.sleep(0.01)
```

We could try making that even smaller, like 0.001 seconds, so we don't potentially fall 10 ms behind.

However, that seems unlikely to be the root cause. Is the fringe pattern caused by us continually falling behind? Can you post a sample data file?

**Comment by meganandd** [comment]
Yes, I'll attach an ACS data .h5 file from a run. 
[acsdata.zip](https://github.com/user-attachments/files/15860446/acsdata.zip)
