### ISSUE TITLE
Divide by zero error when updating ACS plots

### ISSUE THREAD

**Issue by meganandd** [petebachant/TurbineDAQ#99]
I did one test just fine this AM (plots look great!), but now TDAQ is crashing when I try to run the test plan. The error isn't with the data collection itself, but rather when it tries to update plots. Screenshot below:
![div_0_error](https://github.com/petebachant/TurbineDAQ/assets/30161853/fd3e92da-95f3-4505-8346-379e8ebb85db)

**Comment by meganandd** [comment]
Never mind, I figured it out!

**Comment by petebachant** [comment]
> Never mind, I figured it out!

Did the fix require a code change?

**Comment by meganandd** [comment]
Not really no, in-between run 0 and 1 I changed the setting of the feedback velocity filter in ACS to see if it would help with the spikiness on the RPM plot, but that's what was causing the divide by zero error so I changed it back and now it's happy
